# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "familysearch"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jimmy Zimmerman"]
  s.date = "2013-03-18"
  s.description = "A gem for the FamilySearch Platform. Documentation for the FamilySearch Platform can be found at https://"
  s.email = "jimmy.zimmerman@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rvmrc",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/familysearch.rb",
    "lib/familysearch/client.rb",
    "spec/client_spec.rb",
    "spec/familysearch_spec.rb",
    "spec/fixtures/vcr_cassettes/discovery.yml",
    "spec/fixtures/vcr_cassettes/discovery_auth.yml",
    "spec/spec_helper.rb",
    "workspace/notes/APIDesign.txt",
    "workspace/notes/discovery_links.txt",
    "workspace/notes/goals.txt"
  ]
  s.homepage = "http://github.com/jimmyz/familysearch-rb"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "A gem for the FamilySearch Platform."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<faraday>, ["~> 0.8.4"])
      s.add_runtime_dependency(%q<faraday_middleware>, ["~> 0.9.0"])
      s.add_runtime_dependency(%q<multi_json>, ["~> 1.5.0"])
      s.add_runtime_dependency(%q<hashie>, ["~> 2.0.2"])
      s.add_runtime_dependency(%q<rash>, ["~> 0.4.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.13.0"])
      s.add_development_dependency(%q<shoulda>, ["~> 3.3.2"])
      s.add_development_dependency(%q<bundler>, ["~> 1.2.3"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<vcr>, ["~> 2.4.0"])
      s.add_development_dependency(%q<webmock>, ["~> 1.10.0"])
    else
      s.add_dependency(%q<faraday>, ["~> 0.8.4"])
      s.add_dependency(%q<faraday_middleware>, ["~> 0.9.0"])
      s.add_dependency(%q<multi_json>, ["~> 1.5.0"])
      s.add_dependency(%q<hashie>, ["~> 2.0.2"])
      s.add_dependency(%q<rash>, ["~> 0.4.0"])
      s.add_dependency(%q<rspec>, ["~> 2.13.0"])
      s.add_dependency(%q<shoulda>, ["~> 3.3.2"])
      s.add_dependency(%q<bundler>, ["~> 1.2.3"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<vcr>, ["~> 2.4.0"])
      s.add_dependency(%q<webmock>, ["~> 1.10.0"])
    end
  else
    s.add_dependency(%q<faraday>, ["~> 0.8.4"])
    s.add_dependency(%q<faraday_middleware>, ["~> 0.9.0"])
    s.add_dependency(%q<multi_json>, ["~> 1.5.0"])
    s.add_dependency(%q<hashie>, ["~> 2.0.2"])
    s.add_dependency(%q<rash>, ["~> 0.4.0"])
    s.add_dependency(%q<rspec>, ["~> 2.13.0"])
    s.add_dependency(%q<shoulda>, ["~> 3.3.2"])
    s.add_dependency(%q<bundler>, ["~> 1.2.3"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<vcr>, ["~> 2.4.0"])
    s.add_dependency(%q<webmock>, ["~> 1.10.0"])
  end
end

